name: Test Published

on:
  release:
    types: [published]

jobs:
  test_pypi_published:
    name: Upload to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Prepare dist
        run: |
          python3 setup.py sdist
      - name: Delivery package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TEST_PYPI_TOKEN }}
            repository-url: https://test.pypi.org/legacy/

      

  